import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { colors } from './core/variables/colors';
import Link from "next/link";
import { FaUserAstronaut } from "react-icons/fa6";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Swuiuk Language",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${colors.border10} antialiased max-w-md mx-auto border-x h-full bg-black/20 dark:bg-black`}
      >
        <div className="bg-white dark:bg-black pl-5 border-b border-black/10 dark:border-white/40 text-base py-2 montserrat-black w-full text-left flex items-center justify-between px-4">
          <Link href={'/'} className={colors.text}>Swiuk Lang</Link>
          <div className={`${colors.textReverse} ${colors.backgroundReverse} rounded-full border border-cyan-500 px-1 pt-2`}>
            <FaUserAstronaut size={30} />
          </div>
        </div>
        <div  className={colors.background}>
          {children}
        </div>
        {/* <footer className="border-t mt-10 border-black/10 text-black/70 pt-2 text-sm pl-2 w-full">
          Created and designed by Debora Maciel
        </footer> */}
      </body>
    </html>
  );
}
