import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "./core/theme/ThemeContext";
import "./globals.css";
import Navbar from "./core/components/NavBar";
import Layout from "./core/components/Layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Swuiuk Language",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased mx-auto border-x h-screen`}
      >
        <ThemeProvider>
          <Layout>
            <Navbar />
            {children}
          </Layout>
        </ThemeProvider>
        {/* <footer className="border-t mt-10 border-black/10 text-black/70 pt-2 text-sm pl-2 w-full">
          Created and designed by Debora Maciel
        </footer> */}
      </body>
    </html>
  );
}
